### ISSUE TITLE
Coding convention

### ISSUE THREAD

**Issue by baiolo** [bal3no/TrasmissioneFatture#3]
Classes are named with a mix of coding conventions, Eg: `ErroreInvio_Type.php`.
Should we use CamelCase or Snake_Case ?

**Comment by bal3no** [comment]
Yes, that's exactly what I think too. You can try to contribute with a PR on https://github.com/WsdlToPhp/PackageGenerator

**Comment by bal3no** [comment]
just to avoid mistakes, snake case should have only the first letter either upper or lowercase, so the correct class name can to be ErroreInvioType or Errore_invio_type

**Comment by baiolo** [comment]
Why i shoud contribute to another repository if the mistakes are in **this** repository.
May be the mantainer of the other repo is more polite than you @bal3no.
